### PR TITLE
Fix for #25

### PR DESCRIPTION
**Pull request by egamboau**
The issue was caused by a bad array handling on the bash script. Switching to a global variable fixes the issue correctly.

### CODE REVIEW

**Comment by egamboau** [comment]
@taintedzodiac did you check this? This will fix one of the issues reported for the script.

**Comment by roseyhead** [comment]
I've just tried this out and the script looks like it's working (i.e. it cycles through the MAC addresses instead of using the same one) but I'm not actually getting any streetpasses. Any idea what could be going wrong?

**Comment by egamboau** [comment]
Is the 3DS wireless enabled? Is the network configuration correct? In the readme

**Comment by egamboau** [comment]
Bad key and I submitted the comment...

In the readme are some instructions bases on Mac version... Did you follow them? I can't test the script because i'm at work however I will test this as soon as I can

**Comment by roseyhead** [comment]
I forgot to add that the original script worked for me (the first time I ran it) but then running this version didn't seem to do anything. I woke up this morning and gave it another try (using the 'full' parameter) and I got five streetpass hits. Ran it again and didn't get any. It's almost like it's using the same MAC address even though the address in the script's output is cycling correctly.

**Comment by egamboau** [comment]
@roseyhead will check for this and update the pull request accordingly as soon as I get home tonight.

**Comment by roseyhead** [comment]
I'm at work now but when I get home I'll be happy to test it out for you.

**Comment by egamboau** [comment]
@roseyhead I tested the script. Streetpasses worked correctly on two 3DS, one is mine, one is my brother´s one. Both of them received hits without issue. Just a couple of questions:

1. Did you wait for 8 hours to get the new street passes? 
1. Where all the street pass enabled applications on your 3DS empty? For example, enter Mii Plaza, let it read all the street pass data, and then execute the script again.

**Pull request merged**
