### PR TITLE
Update relaymyhome

### PR DESCRIPTION
**Pull request by taintedzodiac**

### CODE REVIEW

**Comment by taintedzodiac** [comment]
@danielhoherd Can you quickly review to confirm this is the proper syntax that you requested be reverted back to? Thanks!

**Comment by danielhoherd** [comment]
@taintedzodiac looks good. I am going to open a supplementary pull request with some additional tweaks.

**Comment by danielhoherd** [comment]
Additional pull created: https://github.com/taintedzodiac/relaymyhome/pull/21

**Comment by danielhoherd** [comment]
I was just looking through the forks of your repo, @taintedzodiac, and wow, @aliang's repo looks like a much better version.  I think you should contact him about pulling that back into your repo.

https://github.com/aliang/relaymyhome/blob/master/relaymyhome

**Pull request merged**
